### ISSUE TITLE
useCombobox focus-ring during keyboard navigation

### ISSUE THREAD

**Issue by jonaskris** [downshift-js/downshift#1595]
- `downshift` version: 8.4.0
- `node` version: @nrwl/node: 15.6.3
- `npm` (or `yarn`) version: npm: 10.2.0

Using the useCombobox hook.

**What you did**:
I tried navigating the combobox using only keyboard navigation.  

**What happened**:
I expected focus-rings as are usual for keyboard navigation. I've searched issues, and google in general to find how focus-rings are implemented in downshift, but cant find any sources or documentation about this.

Hover and highlight are already covered well, but wonder if theres any support for just keyboard navigation, where it's common to highlight the focused element more boldly and distinctly for those who have bad vision.

**Suggested solution**:
Setting some property on the currently keyboard-focused element that can selected in css and styled.

**Comment by nakulnagariy** [comment]
you can use something like this:
js:

```js
<li
                    {...getItemProps({
                      item,
                      index,
                      ...rest,
                    })}
                    className={cn(
                      highlightedIndexItem === index &&
                        item?.disabled !== true &&
                        getBlocksWith("__option-list-item--highlighted"),
                    )}
                  >
```
scss:
```scss
&--highlighted {
        // Goal is to provide a pseudo-focus style when user navigates through menu items via keyboard
        // and a hover style when navigating with a pointer device like a mouse

        &:last-child {
          color: $highlight-color;
          border-block: rem(1) solid $highlight-color;

          &:hover {
            @include standard-hover-visual-styles;

            border-block: none;
          }
        }
      }
```
